name: Makefile
run-name: ${{ github.actor }} is making your files ğŸ“

on:
  push:
    branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#     - name: configure
#       run: ./configure
    - run: echo "Make all"
    - name: make all
      run: make all
    - run: echo "Make bonus"
    - name: make bonus
      run: make bonus
    - run: echo "Make fclean"
    - name: make fclean
      run: make fclean
