name: Norminette
run-name: ${{ github.actor }} is testing out Norminette ğŸ±
on: [push]

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hanshazairi/42-norminette-action@v3
        # optional #
        with:
          exclude-dir: ''
        # optional #
